### Stages

stages:
  - build        # build the project 
  - test       # run its tests


default:
  image: ocaml/opam:debian-12-opam


build:
  stage: build

  cache:
    paths:
      - _opam
      - _build

  script:
    - if [ -d _opam ]; then echo "Dossier _opam existe, rien à installer"; fi
    - >
      if [ ! -d _opam ]; then
        echo "Pas de dossier _opam, création d'un switch"
        opam update
        opam switch create --yes --deps-only --with-test --with-doc . 4.13.0
      fi
    - eval $(opam env)
    - dune build

test:
  stage: test

  cache:
    paths:
      - _opam
      - _build
    policy: pull


  script:
    - eval $(opam env)
    - dune test
